name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Eclipse Temurin JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'# Eclipse Temurin - https://github.com/marketplace/actions/setup-java-jdk#supported-distributions
        java-version: '11'
    - name: Build with Maven
      run: mvn -B -ntp install eu.stamp-project:pitmp-maven-plugin:run sonar:sonar --file pom.xml
      env:
        GITHUB_TOKEN: 116b219c3dcc385340e0d5fb0fd3360534896383
